name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:8.2
    steps:
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example','.env')"
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-sugest
    - name: Generate key
      run: php artisan key:generate